(module styles (render-styles)
  (import scss scheme)

  (define (render-styles)
    (scss->css `(css (html (font "1em Courier"))
                     (li (list-style "none") (padding "3px 0px"))
                     ((// ul li) (display "inline"))
                     ((ol ul) (padding-left "20px"))
                     ((= class wrapper) (display "flex") (height "100%"))
                     ((= class sidebar) (width "20%"))
                     (((= class featured-content) (= class work))
                      (align-items "center")
                      (display "flex")
                      (flex-direction "column")
                      (justify-content "center")
                      (width "80%"))
                     ((= class homepage-link) (color "inherit") (text-decoration "inherit"))))))
